version: "3.7"
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 30s ; python3 ./index.py"
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "chanelworks"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost --silent"]
      timeout: 5s
      retries: 3
    depends_on:
      - mysql
